packages:
  - "apps/*"

catalog:
  # Runtime dependencies
  next: "16.1.6"
  react: "^19.2.4"
  react-dom: "^19.2.4"

  # Dev dependencies
  "@eslint/js": "^9.22.0"
  "@types/node": "^25.2.0"
  "@types/react": "^19.2.11"
  "@types/react-dom": "^19.2.3"
  eslint: "^9.22.0"
  globals: "^16.0.0"
  typescript: "^5.9.3"
  typescript-eslint: "^8.28.0"
